"""Audit packet generation. This is the artifact a CPA or the IRS actually reads,
so it is designed to be self-contained and legible printed in black and white.
"""

import csv
import io
import zipfile
from html import escape
from datetime import date
from decimal import Decimal
from typing import Callable

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    Image,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from . import ledger
from .models import PAYMENT_LABELS, Receipt

STYLES = getSampleStyleSheet()
TITLE = ParagraphStyle("VaultTitle", parent=STYLES["Title"], fontSize=26, spaceAfter=18)
H2 = ParagraphStyle("VaultH2", parent=STYLES["Heading2"], spaceBefore=14)
BODY = ParagraphStyle("VaultBody", parent=STYLES["BodyText"], fontSize=10, leading=14)
SMALL = ParagraphStyle("VaultSmall", parent=STYLES["BodyText"], fontSize=8, leading=11)

TABLE_STYLE = TableStyle(
    [
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.black),
        ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.85, 0.85, 0.85)),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (3, 1), (3, -1), "RIGHT"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.Color(0.95, 0.95, 0.95)]),
    ]
)

def safe(text) -> str:
    """Escape text before it reaches a reportlab Paragraph.

    Paragraph parses a mini-XML markup, so untrusted text is an injection sink:
    '<img src="/etc/passwd"/>' in a provider name makes reportlab read that file
    and embed it in the PDF, and unbalanced markup aborts the whole export.
    Provider, category and description all come from a vision model reading an
    image someone else printed, so none of it is trusted.
    """
    return escape(str(text if text is not None else ""), quote=False)


def para(text, style) -> Paragraph:
    return Paragraph(safe(text), style)


DISCLAIMER = (
    "This document is a personal record of expenses generated by HSAVault. "
    "It is not tax advice. Category names follow IRS-published expense categories; "
    "consult a qualified tax professional about your own eligibility."
)


def _footer(tax_year: int, owner: str):
    def draw(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(colors.black)
        canvas.drawString(
            0.75 * inch, 0.5 * inch, f"HSA Audit Packet — Tax Year {tax_year} — {owner}"
        )
        canvas.drawRightString(LETTER[0] - 0.75 * inch, 0.5 * inch, f"Page {doc.page}")
        canvas.setStrokeColor(colors.black)
        canvas.line(0.75 * inch, 0.62 * inch, LETTER[0] - 0.75 * inch, 0.62 * inch)
        canvas.restoreState()

    return draw


def _fit_image(data: bytes, max_w: float, max_h: float) -> Image | None:
    try:
        reader = ImageReader(io.BytesIO(data))
        width, height = reader.getSize()
    except Exception:
        return None
    scale = min(max_w / width, max_h / height, 1.0)
    return Image(io.BytesIO(data), width=width * scale, height=height * scale)


def _meta_table(receipt: Receipt) -> Table:
    rows = [
        ["Service date", receipt.service_date.isoformat() if receipt.service_date else "—"],
        ["Provider", receipt.provider or "—"],
        ["Amount", f"${receipt.amount:.2f}" if receipt.amount is not None else "—"],
        ["Category", receipt.category],
        ["Payment method", PAYMENT_LABELS.get(receipt.payment_method, receipt.payment_method)],
        [
            "Reimbursed",
            "Yes"
            + (
                f" on {receipt.reimbursement_date.isoformat()}"
                if receipt.reimbursement_date
                else ""
            )
            if receipt.reimbursed
            else (
                f"Partial (${receipt.reimbursement_amount:.2f})"
                if receipt.reimbursement_amount
                else "No"
            ),
        ],
        ["Patient", receipt.patient or "—"],
        ["Description", receipt.description or "—"],
        ["Notes", receipt.notes or "—"],
        ["Receipt ID", receipt.receipt_id],
        ["File hash", receipt.file_hash[:16] + "…" if receipt.file_hash else "—"],
    ]
    table = Table(rows, colWidths=[1.4 * inch, 5.35 * inch])
    table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.Color(0.5, 0.5, 0.5)),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    return table


def build_audit_packet(
    receipts: list[Receipt],
    tax_year: int,
    owner_name: str,
    fetch_image: Callable[[str], bytes] | None = None,
) -> bytes:
    """One PDF for one tax year: cover, summary, subtotals, then a page per receipt."""
    year_receipts = sorted(
        [r for r in ledger.active(receipts) if r.tax_year == tax_year],
        key=lambda r: (r.service_date or date.max, r.provider),
    )

    buffer = io.BytesIO()
    doc = BaseDocTemplate(
        buffer,
        pagesize=LETTER,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.9 * inch,
        title=f"HSA Audit Packet {tax_year}",
        author=owner_name,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="body")
    doc.addPageTemplates(
        [PageTemplate(id="all", frames=[frame], onPage=_footer(tax_year, owner_name))]
    )

    total = sum((r.amount or Decimal("0") for r in year_receipts), Decimal("0"))
    reimbursed = sum(
        (r.reimbursement_amount or Decimal("0") for r in year_receipts), Decimal("0")
    )

    story = [
        Paragraph(f"HSA Audit Packet<br/>Tax Year {tax_year}", TITLE),
        Paragraph(f"<b>{safe(owner_name)}</b>", BODY),
        Spacer(1, 0.3 * inch),
        Table(
            [
                ["Total qualified expenses", f"${total:.2f}"],
                ["Total reimbursed from HSA", f"${reimbursed:.2f}"],
                ["Receipts in this packet", str(len(year_receipts))],
                ["Generated", date.today().isoformat()],
            ],
            colWidths=[3.0 * inch, 3.75 * inch],
            style=TableStyle(
                [
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 11),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                ]
            ),
        ),
        Spacer(1, 0.4 * inch),
        Paragraph(DISCLAIMER, SMALL),
        PageBreak(),
        Paragraph("Summary of receipts", H2),
    ]

    header = ["Date", "Provider", "Category", "Amount", "Payment", "Reimbursed"]
    rows = [header]
    for r in year_receipts:
        rows.append(
            [
                r.service_date.isoformat() if r.service_date else "—",
                para(r.provider or "—", SMALL),
                para(r.category, SMALL),
                f"${r.amount:.2f}" if r.amount is not None else "—",
                "HSA card" if r.payment_method == "hsa_card" else "Out of pocket",
                "Yes" if r.reimbursed else ("Partial" if r.reimbursement_amount else "No"),
            ]
        )
    summary = Table(
        rows,
        colWidths=[0.85 * inch, 1.7 * inch, 1.5 * inch, 0.8 * inch, 0.95 * inch, 0.95 * inch],
        repeatRows=1,
    )
    summary.setStyle(TABLE_STYLE)
    story.append(summary)

    story.append(Paragraph("Category subtotals", H2))
    cat_rows = [["Category", "Receipts", "Amount"]]
    by_cat: dict[str, list[Receipt]] = {}
    for r in year_receipts:
        by_cat.setdefault(r.category, []).append(r)
    for category, items in sorted(
        by_cat.items(), key=lambda kv: sum((r.amount or Decimal("0") for r in kv[1]), Decimal("0")), reverse=True
    ):
        subtotal = sum((r.amount or Decimal("0") for r in items), Decimal("0"))
        cat_rows.append([para(category, SMALL), str(len(items)), f"${subtotal:.2f}"])
    cat_rows.append(["TOTAL", str(len(year_receipts)), f"${total:.2f}"])
    cat_table = Table(cat_rows, colWidths=[3.5 * inch, 1.5 * inch, 1.75 * inch], repeatRows=1)
    cat_table.setStyle(TABLE_STYLE)
    cat_table.setStyle(TableStyle([("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold")]))
    story.append(cat_table)

    for index, receipt in enumerate(year_receipts, start=1):
        story.append(PageBreak())
        label = receipt.provider or "Receipt"
        amount = f"${receipt.amount:.2f}" if receipt.amount is not None else "amount unknown"
        story.append(Paragraph(f"{index}. {safe(label)} — {amount}", H2))
        # Every page, not just the first. A receipt photographed in halves has
        # its total on the last page, so a packet built from drive_file_id alone
        # documents an amount the attached image does not show — the one thing
        # this document exists to avoid.
        file_ids = [i for i in [receipt.drive_file_id, *receipt.extra_file_ids] if i]
        images = []
        if fetch_image:
            for page_no, file_id in enumerate(file_ids, start=1):
                try:
                    fitted = _fit_image(fetch_image(file_id), doc.width, 5.6 * inch)
                except Exception:
                    continue
                if len(file_ids) > 1:
                    images.append(para(f"Page {page_no} of {len(file_ids)}", SMALL))
                images.append(fitted)
                images.append(Spacer(1, 0.15 * inch))
        if images:
            story.extend(images)
        else:
            story.extend(
                [
                    para(
                        "Receipt image not embedded (unsupported format or "
                        "unavailable). Original file: "
                        f"{receipt.drive_link or 'see Drive folder'}",
                        SMALL,
                    ),
                    Spacer(1, 0.15 * inch),
                ]
            )
        story.append(_meta_table(receipt))

    doc.build(story)
    return buffer.getvalue()


def build_csv(receipts: list[Receipt], tax_year: int) -> bytes:
    from .models import RECEIPT_COLUMNS

    year_receipts = [r for r in ledger.active(receipts) if r.tax_year == tax_year]
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(RECEIPT_COLUMNS)
    for r in sorted(year_receipts, key=lambda r: (r.service_date or date.max)):
        writer.writerow(r.to_row())
    return buffer.getvalue().encode("utf-8")


def build_zip(
    receipts: list[Receipt], tax_year: int, fetch_image: Callable[[str], bytes]
) -> bytes:
    """Raw original files for the year, plus the CSV index."""
    year_receipts = [r for r in ledger.active(receipts) if r.tax_year == tax_year]
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(f"HSA_{tax_year}_index.csv", build_csv(receipts, tax_year))
        for r in year_receipts:
            file_ids = [i for i in [r.drive_file_id, *r.extra_file_ids] if i]
            name = f"{r.service_date or 'undated'}__{r.provider or 'unknown'}__{r.file_hash[:8]}"
            for page_no, file_id in enumerate(file_ids, start=1):
                try:
                    data = fetch_image(file_id)
                except Exception:
                    continue
                # Page 1 keeps the original name so existing archives are stable.
                suffix = "" if page_no == 1 else f"__p{page_no}"
                archive.writestr(f"{tax_year}/{name}{suffix}", data)
    return buffer.getvalue()
